server:
  port: 8888
  servlet:
    context-path: /oep-mgt

spring:
  profiles:
    active: local
# ===========thymeleaf配置===========
  thymeleaf:
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html
    encoding: utf-8
    #content-type: text/html
    #mode: HTML5
# ===========静态资源的存放位置配置===========
  resources:
    #static-locations: classpath:/templates/,classpath:/static/


# ===========mybatis-plus===========
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity

---
spring:
# ===========数据源druid配置===========
  profiles: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oep?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password:  lantian,123
# ===========静态页面配置===========
#spring:
#  mvc:
#    view:
#      suffix: .html
#      prefix: views/
#  resources:
#    #描述静态资源的存放位置
#    static-locations: classpath:/templates/,classpath:/static/